### ISSUE TITLE
Inventory changes from Dark/+

### ISSUE THREAD

**Issue by roydukkey** [roydukkey/chimera-theme#8]
**Inventory for January 01, 2019 to August 28, 2020**

- [x] Inventory changes from **Dark** and **Dark+**
  - [ ] Support remote status bar item (#9)
  - [x] Support opt-in to semantic highlighting (#10)
  - [x] Update sidebar section header colors (#11)
  - [x] Fix CPP grammar and themes (#12)
  - [x] Add powershell members to default themes (#13)
- [x] Record why changes were/n't merged
- [x] Create issues (for logical units of work) to complete merger of accepted up-stream changes

Source: https://github.com/microsoft/vscode/tree/master/extensions/theme-defaults/themes

**Comment by roydukkey** [comment]
**Inventory for August 29, 2020 to October 13, 2020**

- [x] Add support for last pinned tab border (#18)

**Comment by roydukkey** [comment]
Will create a milestone for this in the future.
